### ISSUE TITLE
Oro para desbloquear

### ISSUE THREAD

**Issue by alejandro995** [polieduco/Pacto-de-Honor#1]
Como jugador quiero saber cuánto oro tengo para desbloquear un personaje

- [x] Al desbloquear el personaje resta el oro y actualizar @falasias 

- [x] Colocar todos los personajes en nivel 1 @yamideus 

- [x] Verificar que cada uno de los personajes sube experiencia individual en el local storage @yamideus @falasias 

- [x] Relizar pruebas @yamideus 

- [x] Bloquear imágenes de personajes bloqueados @yamideus  (Se agrega en la reunion de Sprint 1)

**Comment by falasias** [comment]
Se completo la verificación de que la experiencia individual de los personajes sube y de que esta actualizando

**Comment by alejandro995** [comment]
Se cierra la historia de usuario
