### ISSUE TITLE
Fin del juego

### ISSUE THREAD

**Issue by alejandro995** [polieduco/Pacto-de-Honor#6]
Como jugador quiero saber cuándo supero/termino el juego

- [x] En el mundo 12 nivel 5 realizar evento (créditos) - fin de juego @falasias  

- [x] Actualizar perfil @Didiazhe  

- [x] Realizar pruebas @yamideus 

- [x] Realizar hash en el local storage @Didiazhe

**Comment by Didiazhe** [comment]
![image](https://user-images.githubusercontent.com/34241391/33630709-549a9d3e-d9d6-11e7-9e9e-6b532b79030b.png)

Localstorage en funcionamiento , anexo imagen.

hice los push con los commits de lo que modifique pero no los veo reflejado aca.

**Comment by alejandro995** [comment]
ponerle seguridad al local storage sprint 2 tarea adicional para el sprint

**Comment by alejandro995** [comment]
Se cierra la historia de usuario
