### ISSUE TITLE
Montar entorno de desarrollo

### ISSUE THREAD

**Issue by alejandro995** [polieduco/Pacto-de-Honor#9]
Como desarrollador  debo tener el proyecto corriendo en un entorno local para empezar con el desarrollo

- [x] Que es phaser, investigacion/tutoriales.

- [x] Clonar repositorio

- [x] Configurar servidor (Apache)

- [x] Verificar funcionamiento

- [x] Crear branch

- [x] Realizar commit con comentarios

- [x] Implementacion y estudio del proyecto en el que se trabajara

**Comment by falasias** [comment]
Se realizaron las tareas propuestas en el issue

**Comment by Didiazhe** [comment]
Se realizo la tarea con éxito.
